server:
  port: 8091
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/donor_search_db
    username: postgres
    password: Alex1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.PostgresPlusDialect
  liquibase:
    change-log: classpath:db/changelog/Changelog.xml
    user: postgres
    password: Alex1234
  web:
    resources:
      static-locations: classpath:/media/

feign:
  client:
    config:
      default:
        readTimeout: 5000
        connectTimeout: 5000
        loggerLevel: FULL

client:
  hackathon: https://hackaton.donorsearch.org/api/

external-service:
  retry:
    attempts: 3
    delay: 3000

logging:
  level:
    root=full:

springdoc:
  packagesToScan: ru.donorsearch.controller