server:
  port: 8091
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://master.9a539aa4-905a-42a8-9eff-549ca5a7c36f.c.dbaas.selcloud.ru:5432/donor_search_db
    username: alex
    password: lqgtnCxydP2D
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.PostgresPlusDialect
  liquibase:
    change-log: classpath:db/changelog/Changelog.xml
    user: alex
    password: lqgtnCxydP2D
  web:
    resources:
      static-locations: classpath:/media/

feign:
  client:
    config:
      default:
        readTimeout: 5000
        connectTimeout: 5000
        loggerLevel: FULL

client:
  hackathon: https://hackaton.donorsearch.org/api/

external-service:
  retry:
    attempts: 3
    delay: 3000

logging:
  level:
    root=full:

springdoc:
  packagesToScan: ru.donorsearch.controller